apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: go-spacemesh-workflow-
spec:
  entrypoint: go-spacemesh
  templates:
  - name: go-spacemesh
    steps:
    - - name: spawn-poet
        template: spawn-poet
    # - - name: spawn-bootstrap
    #     template: spawn-bootstrap
    # - - name: spawn-node
    #     template: spawn-node

  # - name: spawn-poet
  #   script:
  #     image: alpine:latest
  #     command: [kubectl, create, -f, poet-service.yaml]

  # - name: spawn-bootstrap
  #   container:
  #     image: spacemesh/go-spacemesh:latest
  #     imagePullPolicy: Never
  #     command: [/bin/go-spacemesh]
  # - name: spawn-node
  #   container:
  #     image: spacemesh/go-spacemesh:latest
  #     imagePullPolicy: Never
  #     command: [/bin/go-spacemesh]
  #     args: ["--poet-server=10.20.30.40:8000"]
